version: "3"
services:
    webapp:
        build: .
        command: carmel exec -- morbo myapp.pl
    nginx:
        image: nginx:perl
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "8080:80"
